
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 02:40:33 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 30;
  public static final int CONST = 10;
  public static final int CHAR = 3;
  public static final int NAMESPACE = 21;
  public static final int NUMCONST = 49;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int CONTINUE = 18;
  public static final int INT = 2;
  public static final int LSEQ = 32;
  public static final int FOR = 19;
  public static final int MINUS = 23;
  public static final int RPAREN = 43;
  public static final int STATIC = 20;
  public static final int AND = 33;
  public static final int RBOX = 45;
  public static final int LS = 31;
  public static final int OR = 34;
  public static final int COMMA = 40;
  public static final int BOOL = 4;
  public static final int DDOT = 39;
  public static final int CLASS = 8;
  public static final int INC = 36;
  public static final int DIV = 25;
  public static final int PLUS = 22;
  public static final int IF = 11;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 35;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int PERCENT = 26;
  public static final int NULL = 5;
  public static final int DEQUAL = 27;
  public static final int IDENT = 50;
  public static final int BREAK = 7;
  public static final int VOID = 16;
  public static final int LBRACE = 46;
  public static final int ELSE = 9;
  public static final int READ = 14;
  public static final int CHARCONST = 51;
  public static final int NEQUAL = 28;
  public static final int RBRACE = 47;
  public static final int BOOLCONST = 52;
  public static final int EXTENDS = 17;
  public static final int PROG = 6;
  public static final int LBOX = 44;
  public static final int EQGT = 48;
  public static final int DEC = 37;
  public static final int GT = 29;
  public static final int PRINT = 13;
}

